//we need to make a variable to store the EP

@apiEP = http://localhost:8000/api/v1/users    


### Get request
GET {{apiEP}}?id=1&fName=Anish&lName=Lamivhhane

 

###Post Request
POST {{apiEP}}  
Content-Type: application/json      
  
{
    "id" : "5",
    "fName": "Laba",   
    "lName":"Bhandari"   
    
}    

###Delete request
DELETE {{apiEP}}
Content-Type: application/json


### Put Method
PUT {{apiEP}}
Content-Type: application/json 
Authorization: special

{
"id":6,
"fName":"Kush"
}




